language: node_js
node_js:
  - 14
install:
  - npm ci
script:
  - npm run build
jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
        deploy:
          provider: npm
          api_key: $NPM_AUTH_TOKEN
          on: deploy-npm-release
